name:                pisces
version:             0.1.0.0
github:              ob-fun-ws17/studienarbeit-pisces
license:             GPL-3
author:              Fabian Parzefall
maintainer:          fabian.parzefall@mailbox.org
copyright:           2017 Fabian Parzefall

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Reference compiler for a simple language.

description:         Please see the README on Github at <https://github.com/ob-fun-ws17/studienarbeit-pisces>

dependencies:
- base >= 4.8 && < 5
- bytestring
- containers
- llvm-hs
- llvm-hs-pure
- mtl
- parsec

library:
  source-dirs: src

executables:
  pscsc:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pisces

tests:
  pisces-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pisces
    - hspec
